### ISSUE TITLE
Compiling with sound null safety in release mode (webdev) throws type error

### ISSUE THREAD

**Issue by exaby73** [Blimster/deact#2]
# Steps to reproduce

1 .Create simple hello world deact app
2. Serve with `webdev serve -r` for release mode
3. App doesn't load and console shows error

```
Uncaught TypeError: null: type 'minified:b2' is not a subtype of type 'Object'
```

# Environment

Dart: 2.14.3
Deact: 1.0.0 (or any null safe pre-release version)

# Hack to solve

Run without sound null safety. Eg: `webdev serve -n unsound -r`

**Comment by Blimster** [comment]
I just released v1.1.0. Please notice that Dart SDK 2.14 is now required.
